#!/bin/bash

REFERENCE=$1
TEST=$2

if [ -z $LOOPS ]; then
	LOOPS=1
fi

i=1

while (( i <= LOOPS )); do
	SEED=$RANDOM

	echo "Doing loop" $i "with the seed" $SEED"..."
	if diff <(./$REFERENCE $SEED) <(./$TEST $SEED); then
		echo "OK"
	else
		echo "Fail"
		exit 1
	fi

	i=$(( i + 1 ))
done

exit 0
